# Generated by Django 2.2.1 on 2020-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catdex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'name'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='domain',
            field=models.CharField(choices=[('쪽문', '쪽문'), ('서문', '서문'), ('솔로문', '솔로문'), ('동문', '동문'), ('대학원동', '대학원동'), ('화학관', '화학관'), ('향토/첨성', '향토/첨성')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cat',
            name='tnr',
            field=models.CharField(choices=[('중성화YES', '중성화YES'), ('중성화NO', '중성화NO')], db_index=True, max_length=200),
        ),
    ]
