# Generated by Django 2.2.1 on 2020-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_photo')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
